//! Acceptance §7 items 3 and 5, the run half: the shared scripted cases
//! drive every routing tier, failure policy, goal gate, fan-out and
//! `loop_restart` through a real run under stubs — and each result is
//! compared with the committed Fabro oracle fixture for the same case
//! (`crates/fabro/oracle/expected/<case>.json`), generated by running the
//! pinned Fabro binary through `scripts/oracle-regenerate.sh`. Every fixture
//! must name the pinned Fabro commit; a fixture from another revision is
//! rejected, so fixtures and parity runs always use one reference version. A
//! case whose fixture records a deliberate departure is compared with the
//! departure recorded.

use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};
use std::{env, fs};

use fabro_acceptance::pin;
use fabro_acceptance::runs::{Case, RunResult, result_json};
use serde_json::{Value, json};

fn oracle_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../oracle")
}

fn cases() -> Vec<Case> {
    let mut paths: Vec<PathBuf> = fs::read_dir(oracle_dir().join("cases"))
        .expect("the cases directory")
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "json"))
        .collect();
    paths.sort();
    paths.iter().map(|p| Case::load(p)).collect()
}

async fn run_case(case: &Case) -> RunResult {
    case.run().await
}

fn assert_path(result: &RunResult, status: &str, path: &[&str]) {
    assert_eq!(result.status, status, "{result:?}");
    assert_eq!(result.nodes(), path, "{result:?}");
}

async fn run_named(name: &str) -> RunResult {
    let case = Case::load(&oracle_dir().join("cases").join(format!("{name}.json")));
    run_case(&case).await
}

#[tokio::test]
async fn tier_one_conditions_pick_by_weight_then_lexical_target() {
    let r = run_named("tier1_condition_picks_highest_weight_then_lexical").await;
    assert_path(&r, "success", &["start", "a", "c", "exit"]);
    let r = run_named("tier1_condition_lexical_tiebreak").await;
    assert_path(&r, "success", &["start", "a", "alpha", "exit"]);
}

#[tokio::test]
async fn tier_two_preferred_label_beats_suggested_ids() {
    let r = run_named("tier2_preferred_label_beats_suggested_and_fallback").await;
    assert_path(&r, "success", &["start", "a", "fix", "exit"]);
}

#[tokio::test]
async fn tier_three_suggested_ids_in_order() {
    let r = run_named("tier3_suggested_ids_lowest_index_wins").await;
    assert_path(&r, "success", &["start", "a", "p2", "exit"]);
}

#[tokio::test]
async fn tier_four_fallback_follows_the_failure_policy() {
    let r = run_named("tier4_fallback_route_on_failure").await;
    assert_path(&r, "success", &["start", "a", "b", "exit"]);
    assert_eq!(r.path[1].outcome, "failed");
    let r = run_named("tier4_exit_policy_ends_the_run_failed").await;
    assert_path(&r, "failed", &["start", "a"]);
    let r = run_named("tier4_exit_policy_still_takes_an_explicit_failure_edge").await;
    assert_path(&r, "success", &["start", "a", "recover", "exit"]);
}

#[tokio::test]
async fn context_signals_route_conditionals() {
    let r = run_named("conditional_node_routes_on_previous_outcome_via_context").await;
    assert_path(&r, "success", &["start", "work", "gate", "exit"]);
    let r = run_named("custom_routing_signal_rides_context").await;
    assert_path(&r, "success", &["start", "a", "fast", "exit"]);
    assert_eq!(r.context.get("mode"), Some(&Value::String("fast".into())));
}

#[tokio::test]
async fn human_gates_route_on_the_answer_and_never_fall_through_on_failure() {
    let r = run_named("human_gate_answer_selects_its_edge").await;
    assert_path(&r, "success", &["start", "gate", "no", "exit"]);
    let r = run_named("human_gate_failure_does_not_fall_through").await;
    assert_path(&r, "failed", &["start", "gate"]);
}

#[tokio::test]
async fn retries_and_exhaustion_follow_fabro() {
    let r = run_named("retry_requested_then_success").await;
    assert_path(&r, "success", &["start", "a", "exit"]);
    assert_eq!(r.path[1].outcome, "succeeded");
    let r = run_named("retries_exhausted_allow_partial").await;
    assert_path(&r, "success", &["start", "a", "b", "exit"]);
    assert_eq!(r.path[1].outcome, "partially_succeeded");
    let r = run_named("retries_exhausted_stays_failed").await;
    assert_path(&r, "success", &["start", "a", "recover", "exit"]);
    let r = run_named("allow_partial_at_one_attempt").await;
    assert_path(&r, "success", &["start", "a", "exit"]);
    assert_eq!(r.path[1].outcome, "partially_succeeded");
}

#[tokio::test]
async fn goal_gates_send_the_run_back_to_their_retry_target_or_fail_it() {
    let r = run_named("goal_gate_unsatisfied_returns_to_retry_target_then_passes").await;
    assert_path(&r, "success", &[
        "start", "work", "verify", "work", "verify", "exit",
    ]);
    let r = run_named("goal_gate_unsatisfied_without_target_fails").await;
    assert_path(&r, "failed", &["start", "work", "verify"]);
}

#[tokio::test]
async fn static_fan_out_joins_every_branch() {
    let r = run_named("static_fan_out_joins_all_branches").await;
    assert_eq!(r.status, "success", "{r:?}");
    let nodes = r.nodes();
    assert_eq!(&nodes[..2], &["start", "fork"]);
    assert_eq!(&nodes[4..], &["merge", "report", "exit"]);
    assert!(nodes[2..4].contains(&"a") && nodes[2..4].contains(&"b"));
}

#[tokio::test]
async fn loop_restart_produces_a_successor_execution() {
    let r = run_named("loop_restart_starts_a_successor_execution").await;
    assert_eq!(r.status, "success", "{r:?}");
    assert_eq!(r.executions, 2);
    assert_eq!(
        r.nodes(),
        ["start", "work", "check", "work", "check", "exit"],
        "both executions in order; the successor starts at the restart target"
    );
}

#[tokio::test]
async fn skipped_and_partial_outcomes_route_as_fabro_documents() {
    let r = run_named("skipped_outcome_routes_like_success").await;
    assert_path(&r, "success", &["start", "a", "b", "exit"]);
    // Petri's `partially_succeed` extension follows Fabro's promotion order:
    // the explicit failure edge wins and the stage stays failed.
    let r = run_named("partially_succeed_policy_classifies_before_routing").await;
    assert_path(&r, "success", &["start", "a", "recover", "exit"]);
    assert_eq!(r.path[1].outcome, "failed");
}

/// Fabro's promotion order under `on_failure="succeed"`: a failure an
/// explicit route matches (a condition, a preferred label) stays failed and
/// takes that route; a failure no explicit route matches is promoted and
/// reports `succeeded`, as the pinned Fabro's events show it.
#[tokio::test]
async fn succeed_promotes_only_a_failure_no_explicit_route_matches() {
    let r = run_named("succeed_keeps_a_failure_an_explicit_edge_matches").await;
    assert_path(&r, "success", &["start", "a", "recover", "exit"]);
    assert_eq!(r.path[1].outcome, "failed");
    let r = run_named("succeed_keeps_a_failure_a_preferred_label_matches").await;
    assert_path(&r, "success", &["start", "a", "fix", "exit"]);
    assert_eq!(r.path[1].outcome, "failed");
    let r = run_named("succeed_promotes_a_failure_no_explicit_edge_matches").await;
    assert_path(&r, "success", &["start", "a", "ok", "exit"]);
    assert_eq!(r.path[1].outcome, "succeeded");
}

/// Every shared case against its committed Fabro oracle fixture. The fixture
/// holds Fabro's result; a case with a recorded departure holds Petri's
/// expected result beside Fabro's, and the test checks Petri against that.
/// A fixture whose Fabro result is `rejected` (Fabro's validator refused the
/// workflow) must carry a departure: Petri accepting the spelling is itself a
/// recorded difference.
/// With `PETRI_ORACLE_RECORD=1` (what `scripts/oracle-regenerate.sh` sets)
/// the test writes Petri's result into the fixture of every departure case
/// instead of checking it.
#[tokio::test]
#[expect(
    clippy::print_stderr,
    reason = "a missing fixture is reported on stderr with the command that generates it"
)]
async fn every_case_matches_the_fabro_oracle() {
    let cell = CoverageCell::start("routing/tiers-oracle@host/none");
    let expected_dir = oracle_dir().join("expected");
    let record = env::var("PETRI_ORACLE_RECORD").is_ok_and(|v| !v.is_empty());
    let pinned = pin();
    let mut missing = Vec::new();
    let mut mismatches = Vec::new();
    let mut wrong_revision = Vec::new();
    for case in cases() {
        let path = expected_dir.join(format!("{}.json", case.name));
        let Ok(text) = fs::read_to_string(&path) else {
            missing.push(case.name.clone());
            continue;
        };
        let mut fixture: Value =
            serde_json::from_str(&text).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        let commit = fixture["fabro_commit"].as_str().unwrap_or("");
        if commit != pinned {
            wrong_revision.push(format!("{}: fixture is from `{commit}`", case.name));
            continue;
        }
        let actual = result_json(&run_case(&case).await);
        if case.departure.is_some() && record {
            fixture["petri"] = actual;
            fs::write(
                &path,
                format!(
                    "{}\n",
                    serde_json::to_string_pretty(&fixture).expect("json")
                ),
            )
            .expect("write the fixture");
            continue;
        }
        let fabro_rejected = fixture["fabro"]["status"] == "rejected";
        assert!(
            !fabro_rejected || case.departure.is_some(),
            "{}: Fabro rejected the workflow but the case records no departure",
            case.name
        );
        let expected = if case.departure.is_some() {
            fixture.get("petri").cloned().unwrap_or(Value::Null)
        } else {
            fixture["fabro"].clone()
        };
        if actual != expected {
            mismatches.push(format!(
                "{}:\n  expected {}\n  actual   {}",
                case.name,
                serde_json::to_string(&expected).expect("json"),
                serde_json::to_string(&actual).expect("json")
            ));
        }
    }
    if !missing.is_empty() {
        eprintln!(
            "no oracle fixture for: {}; run scripts/oracle-regenerate.sh",
            missing.join(", ")
        );
    }
    assert!(
        missing.is_empty(),
        "every case has a committed Fabro oracle fixture"
    );
    assert!(
        wrong_revision.is_empty(),
        "every fixture is generated from the pinned Fabro `{pinned}`; mixed revisions are \
         rejected. Run scripts/oracle-regenerate.sh:\n  {}",
        wrong_revision.join("\n  ")
    );
    assert!(
        mismatches.is_empty(),
        "oracle mismatches:\n{}",
        mismatches.join("\n")
    );
    cell.pass();
}

/// The black box coverage report's per-cell record for the matrix cell this
/// test satisfies. The shape is the one `crates/petri/cli/tests/support/fabro/
/// scenario.rs` writes: a `failed` record on start, so a panic leaves a
/// failure on file, and `passed` at the end. The report only counts `passed`.
struct CoverageCell {
    path:   PathBuf,
    cell:   &'static str,
    passed: bool,
}

impl CoverageCell {
    fn start(cell: &'static str) -> Self {
        let dir = env::var_os("PETRI_FABRO_COVERAGE_DIR").map_or_else(
            || Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../target/fabro-coverage/results"),
            PathBuf::from,
        );
        let _ = fs::create_dir_all(&dir);
        let record = Self {
            path: dir.join(format!("{}.json", cell.replace(['/', '@'], "__"))),
            cell,
            passed: false,
        };
        record.write("failed", Some("the test did not report a pass"));
        record
    }

    fn pass(mut self) {
        self.passed = true;
        self.write("passed", None);
    }

    fn write(&self, status: &str, note: Option<&str>) {
        let record = json!({
            "cell": self.cell,
            "status": status,
            "note": note,
            "recorded_at": SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map(|d| d.as_secs())
                .unwrap_or_default(),
        });
        let _ = fs::write(
            &self.path,
            serde_json::to_vec_pretty(&record).unwrap_or_default(),
        );
    }
}

impl Drop for CoverageCell {
    fn drop(&mut self) {
        if !self.passed {
            self.write("failed", Some("the test ended without reporting a pass"));
        }
    }
}
